### ISSUE TITLE
Retorno em blocos

### ISSUE THREAD

**Issue by jairoataide** [TeoCalvo/teoSQL#3]
Opaaa @TeoCalvo,

Ao gerar a seguinte query retorna os resultados em forma de tabela:
SELECT *
FROM tb_products;

Contudo se desejo que a forma de retorno seja um bloco para cada grupo de registro, como exemplificado abaixo, qual seria a melhor forma? Tentei pelo PIVOT, mas não retornou exatamente assim.

product_id                             | 00066f42aeeb9f3007548bb9d3f33c38
product_category_name       | perfumaria
product_name_lenght           | 53
product_description_lenght  | 596
product_photos_qty              | 6
product_weight_g                 | 300
product_length_cm               | 20
product_height_cm               | 16
product_width_cm                | 16
  
product_id                            | 00088930e925c41fd95ebfe695fd2655
product_category_name      | automotivo
product_name_lenght          | 56
product_description_lenght | 752
product_photos_qty             | 4
product_weight_g                | 1225
product_length_cm             | 55
product_height_cm             | 10
product_width_cm              | 26
   
product_id                            | 0009406fd7479715e4bef61dd91f2462
product_category_name      | cama_mesa_banho
product_name_lenght          | 50
product_description_lenght | 266
product_photos_qty             | 2
product_weight_g                | 300
product_length_cm              | 45
product_height_cm              | 15
product_width_cm               | 35

**Comment by TeoCalvo** [comment]
Jairo, no SQLite não temos uma função que realize o pivot das tabelas. Minhas sugestão seria trabalhar com a porção de dados de interesse e realizasse este procedimento de "transpose" ou "pivot" em outra ferramenta, como Python, SAS, R, etc.

**Comment by jairoataide** [comment]
Entendido ;-)
