### ISSUE TITLE
arquivo indisponível no drive

### ISSUE THREAD

**Issue by renatond** [TeoCalvo/teoSQL#4]
Fala Teo, tudo bem? Rapaz, o arquivo olist.db não está disponível mais no google drive, será que pode atualizar?

**Comment by TeoCalvo** [comment]
Feito! Atualizei o link no readMe e vc pode conferir aqui tbm: https://drive.google.com/file/d/12jKtfHsvDz8hGznIKffK-fZAsaKfsA8W/view?usp=sharing
